# Parameter file: read by rfinder.py
#     This is a secondary parameter file for executing the rfinder code.
# 
# Matthew R. Carbone & Marco Baity-Jesi
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Number of Monte-Carlo timesteps
nmc:             50000

delta:
  n:             100
  log_grid:      False
  minimum:       0.01    # Note this corresponds to the base if log_grid
  maximum:       300     # ^

beta:
  n:             100
  log_grid:      False
  minimum:       0.5
  maximum:       1.5

dim:
  n:             100
  log_grid:      False
  minimum:       3
  maximum:       30

x0:
  n:             100
  log_grid:      True
  minimum:       -3
  maximum:       1
